### ISSUE TITLE
ETF iShares Core EURO STOXX 50 appears as a Stock

### ISSUE THREAD

**Issue by jmgomezpoveda** [pviotti/degiro-bookkeeper#98]
ETF "iShares Core EURO STOXX 50 UCITS ETF EUR (Acc)" (https://live.euronext.com/en/product/etfs/IE00B53L3W79-XAMS) appears in the DeGiro CSV file as "iSHR ESTX50 B A":

> "[...],Buy 11 iSHR ESTX50 B A@132.52 EUR (IE00B53L3W79),[...]"

Since the name contains iSHR and not ISHARES, it is not being counted as an ETF.

It would appear that this needs a fix in Degiro.Account/Degiro.fs, in the etfDescriptionMarkers array.

Workaround: Edit the CSV before processing, as follows:

> cat Account.csv | sed 's/ iSHR / ISHARES /g' > Account-fixed.csv

**Comment by pviotti** [comment]
good catch, thanks for reporting this! It's been fixed as suggested in #102 , will be part of the next release.
As you noticed, unfortunately, telling apart ETF from stock in the account statement is a bit tricky.
